# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a92a3ad5fd33eca92e14b4a5caba3c1739983427d9ef0b07ec9e0d31597952b2c21a5959a15c0adc6980fa674ca079817753b4c05a3a48648cd92c5bc18bc5f9

test:
  secret_key_base: 1f61ac3ece8da26a990fe0b66dea1ea84dc1f3b257edab0a12713efe4e23bb76d3dea9ceb9981091157d8ba75f8e56ac0d4775afae7f80f231e684726ea169ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
